Create Calmcoder.xml
ricardograca/gedit-themes pull request #13
Opened 2016-06-08 17:26 UTC by vikaskyadav

A simple,elegant and colorful color-theme for coders.

2016-06-08 21:00 UTC, ricardograca commented
Thanks! I'll check it out later today or tomorrow and either respond back with any questions/issues or merge it.

2017-12-19 15:24 UTC, ricardograca commented
After reviewing it (sorry it took this long) I'm not a big fan of the particular shade of purple used for some keywords. This makes them quite a bit hard to read against the green background:

![Calm Coder gedit theme preview](https://user-images.githubusercontent.com/1457035/34164083-83ec6662-e4d0-11e7-9658-b2b1b69f93df.png)

Everything else looks good to me. Do you have any intention of reviewing this?

2017-12-19 19:15 UTC, vikaskyadav commented
Yeah. I will be more than happy. Suggest me some changes.  I will try to
implement those within this week.!

On Tue, Dec 19, 2017 at 8:54 PM, Ricardo Graça <notifications@github.com>
wrote:

> After reviewing it (sorry it took this long) I'm not a big fan of the
> particular shade of purple used for some keywords. This makes them quite a
> bit hard to read against the green background:
>
> [image: Calm Coder gedit theme preview]
> <https://user-images.githubusercontent.com/1457035/34164083-83ec6662-e4d0-11e7-9658-b2b1b69f93df.png>
>
> Everything else looks good to me. Do you have any intention of reviewing
> this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ricardograca/gedit-themes/pull/13#issuecomment-352790786>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMBh16hHaqnw7s3coPISj_YEwnwVsi_4ks5tB9UbgaJpZM4IxNFV>
> .
>

2017-12-19 23:42 UTC, ricardograca commented
Just the purple color that's a bit hard to read. Everything else looks good.

2017-12-20 11:33 UTC, ricardograca requested changes
After you fix the invalid XML issue I'll merge it. Looks good to me otherwise.

2017-12-20 11:33 UTC, ricardograca commented on Calmcoder.xml
> +  <?xml version="1.0" encoding="UTF-8"?>
These two spaces you added here made the XML document invalid and caused it to not be detected by Gedit.

2017-12-20 11:33 UTC, ricardograca commented on Calmcoder.xml
> +  <style name="def:error" foreground="#f8f8f0" background="#ffcc66"/>
Looks good to me, good job :+1:

2017-12-20 17:57 UTC, ricardograca approved these changes

2017-12-20 17:58 UTC, merged